"""add autopilot flag, ai engine config, contact messages

Revision ID: 0509f9badea8
Revises: 155e5745a48c
Create Date: 2026-07-13 17:30:57.532872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0509f9badea8'
down_revision: Union[str, None] = '155e5745a48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_engine_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rsi_weight', sa.Float(), nullable=False),
    sa.Column('macd_weight', sa.Float(), nullable=False),
    sa.Column('ema_weight', sa.Float(), nullable=False),
    sa.Column('bollinger_weight', sa.Float(), nullable=False),
    sa.Column('sma_weight', sa.Float(), nullable=False),
    sa.Column('buy_threshold', sa.Float(), nullable=False),
    sa.Column('sell_threshold', sa.Float(), nullable=False),
    sa.Column('autopilot_confidence_floor', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_created_at'), 'contact_messages', ['created_at'], unique=False)
    op.add_column(
        'users',
        sa.Column(
            'auto_trade_enabled', sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auto_trade_enabled')
    op.drop_index(op.f('ix_contact_messages_created_at'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_table('ai_engine_config')
    # ### end Alembic commands ###
