"""add role, is_active, equity snapshots

Revision ID: 155e5745a48c
Revises: 92ecc60727eb
Create Date: 2026-07-13 16:35:35.925658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155e5745a48c'
down_revision: Union[str, None] = '92ecc60727eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equity_snapshots_recorded_at'), 'equity_snapshots', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_equity_snapshots_user_id'), 'equity_snapshots', ['user_id'], unique=False)
    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.Enum('user', 'admin', name='userrole'),
            nullable=False,
            server_default='user',
        ),
    )
    op.add_column(
        'users',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_equity_snapshots_user_id'), table_name='equity_snapshots')
    op.drop_index(op.f('ix_equity_snapshots_recorded_at'), table_name='equity_snapshots')
    op.drop_table('equity_snapshots')
    # ### end Alembic commands ###
