"use client";

import { useEffect, useState } from "react";
import clsx from "clsx";
import { TrendingUp, TrendingDown, Minus, Sparkles } from "lucide-react";
import { api, AIRecommendation, MarketSummary } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";

const ACTION_META: Record<string, { label: string; icon: typeof TrendingUp; className: string }> = {
  BUY: { label: "Bullish", icon: TrendingUp, className: "text-success bg-success/15" },
  SELL: { label: "Bearish", icon: TrendingDown, className: "text-danger bg-danger/15" },
  HOLD: { label: "Neutral", icon: Minus, className: "text-muted bg-surface-2" },
};

const POLL_MS = 8000;

export default function MarketIntelligencePage() {
  const { token } = useAuth();
  const [recs, setRecs] = useState<AIRecommendation[]>([]);
  const [summary, setSummary] = useState<MarketSummary | null>(null);
  const [summaryLoading, setSummaryLoading] = useState(false);

  useEffect(() => {
    if (!token) return;
    let cancelled = false;

    async function load() {
      const data = await api.recommendations(token!);
      if (!cancelled) setRecs(data);
    }

    load();
    const id = setInterval(load, POLL_MS);
    return () => {
      cancelled = true;
      clearInterval(id);
    };
  }, [token]);

  async function loadSummary() {
    if (!token) return;
    setSummaryLoading(true);
    try {
      setSummary(await api.adminMarketSummary(token));
    } finally {
      setSummaryLoading(false);
    }
  }

  useEffect(() => {
    loadSummary();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [token]);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold">Market Intelligence</h1>
        <p className="mt-1 text-sm text-muted">
          The AI engine's current read on every tracked symbol, in one place.
        </p>
      </div>

      <div className="glass rounded-2xl p-6">
        <div className="flex items-center justify-between">
          <p className="flex items-center gap-2 font-semibold">
            <Sparkles size={16} className="text-accent" /> AI Summary
          </p>
          <button
            onClick={loadSummary}
            disabled={summaryLoading}
            className="text-xs text-accent hover:underline disabled:opacity-50"
          >
            {summaryLoading ? "Refreshing..." : "Refresh"}
          </button>
        </div>
        <p className="mt-3 text-sm leading-relaxed text-foreground">
          {summary?.summary ?? (summaryLoading ? "Analyzing markets..." : "—")}
        </p>
        {summary && (
          <p className="mt-2 text-xs text-muted">
            Generated by {summary.generated_by === "claude" ? "Claude" : "rule-based template"}
          </p>
        )}
      </div>

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        {recs.map((r) => {
          const meta = ACTION_META[r.action];
          const Icon = meta.icon;
          return (
            <div key={r.symbol} className="glass rounded-2xl p-5">
              <div className="flex items-start justify-between">
                <div>
                  <p className="text-lg font-semibold">{r.symbol}</p>
                  <p className="text-xs text-muted">${r.price.toLocaleString(undefined, { maximumFractionDigits: 2 })}</p>
                </div>
                <span className={clsx("flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs font-medium", meta.className)}>
                  <Icon size={14} /> {meta.label}
                </span>
              </div>
              <div className="mt-4 flex items-center justify-between text-sm">
                <span className="text-muted">Confidence</span>
                <span className="font-medium">{r.confidence.toFixed(0)}%</span>
              </div>
              <div className="mt-1 flex items-center justify-between text-sm">
                <span className="text-muted">Risk</span>
                <span className="font-medium">{r.risk_level}</span>
              </div>
              <p className="mt-3 text-xs text-muted">{r.reasons[0]}</p>
            </div>
          );
        })}
      </div>
    </div>
  );
}
